[tool.poetry]
name = "client"
version = "0.1.0"
description = ""
authors = ["fschwanck <fschwanck@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
pytest = "^7.2.1"
flwr = "^1.3.0"
torch = "^1.13.1"
torchvision = "^0.14.1"
numpy = "^1.24.2"
seaborn = "^0.12.2"
matplotlib = "^3.7.1"
scikit-learn = "^1.2.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
