FROM python:3.12 AS base

WORKDIR /

RUN apt update -y && apt upgrade -y
RUN pip install --upgrade pip && pip install pipenv

ADD ./Pipfile /
ADD ./Pipfile.lock /

FROM base AS runtime

RUN pipenv install --deploy --system
ADD ./src/server /server
ADD ./.cache/certificates .cache/certificates



CMD [ "python","-u","-m","server.main" ]
