version: '3'

services:

  fl-framework-server:
    image: 'fschwanck/fl-framework-server:latest'
    env_file:
      - ./common.env
      - ./server.env
    networks:
      - mynet
      
    restart: always
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type==manager
    volumes:
    - ./data:/data
    - ./experiments:/experiments






  fl-framework-client-0:
    image: 'fschwanck/fl-framework-client:latest'
    env_file:
      - ./common.env
      - ./client.env
    environment:
      - CLIENT_ID=0
      - FLWR_TELEMETRY_ENABLED=0


      
    networks:
      - mynet
    restart: always
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type==worker
    volumes:
    - ./data:/data
    - ./experiments:/experiments
      

  fl-framework-client-1:
    image: 'fschwanck/fl-framework-client:latest'
    env_file:
      - ./common.env
      - ./client.env
    environment:
      - CLIENT_ID=1
      - FLWR_TELEMETRY_ENABLED=0
      
    networks:
      - mynet

    restart: always
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type==worker
    volumes:
    - ./data:/data
    - ./experiments:/experiments
    
  fl-framework-client-2:
    image: 'fschwanck/fl-framework-client:latest'
    env_file:
      - ./common.env
      - ./client.env
    environment:
      - CLIENT_ID=2
      - FLWR_TELEMETRY_ENABLED=0
      

      
    networks:
      - mynet
    restart: always
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type==worker
    volumes:
    - ./data:/data
    - ./experiments:/experiments
  
  fl-framework-client-3:
    image: 'fschwanck/fl-framework-client:latest'
    env_file:
      - ./common.env
      - ./client.env
    environment:
      - CLIENT_ID=3
      - FLWR_TELEMETRY_ENABLED=0

      
    networks:
      - mynet
    restart: always
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type==worker
    volumes:
    - ./data:/data
    - ./experiments:/experiments

  fl-framework-client-4:
    image: 'fschwanck/fl-framework-client:latest'
    env_file:
      - ./common.env
      - ./client.env
    environment:
      - CLIENT_ID=4
      - FLWR_TELEMETRY_ENABLED=0

      
    networks:
      - mynet
    restart: always
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type==worker
    volumes:
    - ./data:/data
    - ./experiments:/experiments
 
networks:
  mynet:
    driver: overlay
    attachable: true
    ipam:
      config:
        - subnet: 10.5.0.0/16
          aux_addresses:
            server: 10.5.0.2
         
            
