apiVersion: apps/v1
kind: Deployment
metadata:
  name: fl-framework-cifar
  labels:
    app.kubernetes.io/component: fl-framework
    app.kubernetes.io/name: fl-framework-cifar
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: fl-framework
      app.kubernetes.io/name: fl-framework-cifar
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: fl-framework
        app.kubernetes.io/name: fl-framework-cifar
    spec:
      containers:
        - name: client2
          image: 'fschwanck/fl-framework-client:latest'
          env:
            - name: FL_CLIENT_DEVICE
              value: cpu
            - name: CERTIFICATES_PATH
              value: ./.cache/certificates
            - name: SERVER_ADDRESS
              value: fl_server:8080
            - name: DATA_PATH
              value: ./data/cifar-10
          volumeMounts:
            - name: VOLUME_NAME
              mountPath: MOUNT_PATH
              subPath: SUB_PATH
      nodeSelector:
        kubernetes.io/hostname: mac-porvir-03
