apiVersion: apps/v1
kind: Deployment
metadata:
  name: fl-framework-server
  labels:
    app.kubernetes.io/component: fl-framework
    app.kubernetes.io/name: fl-framework-server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: fl-framework
      app.kubernetes.io/name: fl-framework-server
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: fl-framework
        app.kubernetes.io/name: fl-framework-server
    spec:
      containers:
        - name: server
          image: 'fschwanck/fl-framework-server:latest'
          imagePullPolicy: IfNotPresent
          ports:
            - name: fl_server
              containerPort: 8080
          env:
            - name: SERVER_NUM_ROUNDS
              value: '1'
            - name: CERTIFICATES_PATH
              value: ./.cache/certificates
            - name: SERVER_ADDRESS
              value: 0.0.0.0:8080
            - name: FRACTION_FIT
              value: '2'
            - name: MIN_FIT_CLIENTS
              value: '2'
            - name: MIN_AVAILABLE_CLIENTS
              value: '2'
      nodeSelector:
        kubernetes.io/hostname: mac-porvir-01
