apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fl-framework-storageclaim
  namespace: elpeixoto
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: rook-ceph-fs-simple



