apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fl-framework-storageclaim
  namespace: fschwanck
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: rook-cephfs



